---
abstract: 'No more module loading!'
author:
  - 'Josh Jore <jjore@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200000, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-Nothing
requires:
  perl: 5.8.0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Acme-Nothing
  homepage: http://search.cpan.org/dist/Acme-Nothing
  repository: git://github.com/jbenjore/acme-nothing.git
version: 0.03
